# Generated by Django 5.1.7 on 2025-03-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama/Tanıtım Yazısı')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage_images/', verbose_name='Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Ana Sayfa İçeriği',
                'verbose_name_plural': 'Ana Sayfa İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_code', models.CharField(max_length=20, unique=True)),
                ('disease', models.TextField(blank=True, null=True)),
                ('blood_test', models.FileField(blank=True, null=True, upload_to='blood_tests/')),
                ('diet_program', models.TextField(blank=True, null=True)),
                ('previous_treatments', models.TextField(blank=True, null=True)),
                ('is_consultant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
