# Generated by Django 5.1.7 on 2025-03-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+90 555 555 55 55', max_length=20)),
                ('email', models.EmailField(default='info@menekseler.com', max_length=254)),
                ('address', models.TextField(default='Firmanın adres bilgisi buraya yazılabilir.')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
            ],
        ),
    ]
