# Generated by Django 5.1.7 on 2025-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagecontent_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doküman',
                'verbose_name_plural': 'Dokümanlar',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='documents',
            field=models.TextField(blank=True, help_text='HTML içerik olarak dokümanlara giriş yazısı eklenebilir', null=True),
        ),
    ]
