# Generated by Django 5.1.7 on 2025-03-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_document_homepagecontent_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('address', models.TextField(verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'İletişim Bilgileri',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name': 'Ana Sayfa İçeriği', 'verbose_name_plural': 'Ana Sayfa İçeriği'},
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Doküman Başlığı'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Görseli'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Ana Sayfa Metni'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='documents',
            field=models.TextField(blank=True, help_text='HTML içerik olarak dokümanlara giriş yazısı eklenebilir', null=True, verbose_name='Dokümanlar Sayfası Metni'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='homepage_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Ana Sayfa Görseli'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Site Logosu'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(default='Menekşeler', max_length=100, verbose_name='Site Başlığı'),
        ),
    ]
