# Generated by Django 5.1.7 on 2025-03-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactinfo_alter_homepagecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(default='905555555555', help_text='Örnek: 905551234567 (Başında 90 olmalı, boşluk olmamalı)', max_length=20, verbose_name='WhatsApp Numarası'),
        ),
    ]
