# Generated by Django 5.1.7 on 2025-03-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactinfo_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_description', models.TextField(default='Your trusted partner in healthy eating and nutritional guidance.', verbose_name='Footer Açıklaması')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook Linki')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter Linki')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/menekseler2025', verbose_name='Instagram Linki')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Linki')),
            ],
            options={
                'verbose_name': 'Footer Ayarları',
                'verbose_name_plural': 'Footer Ayarları',
            },
        ),
    ]
