# Generated by Django 5.1.7 on 2025-03-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='twitter_url',
        ),
    ]
