# Generated by Django 5.1.7 on 2025-03-31 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_footersettings_twitter_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hedef Kilo')),
                ('daily_calories', models.IntegerField(verbose_name='Günlük Kalori')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Diyet Programı',
                'verbose_name_plural': 'Diyet Programları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_description',
            field=models.TextField(default='Menekşeler Diyet ve Sağlıklı Yaşam Merkezi olarak, size özel diyet programları ve sağlıklı yaşam önerileri sunuyoruz.', verbose_name='Footer Açıklaması'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('snack', 'Ara Öğün')], max_length=10, verbose_name='Öğün Tipi')),
                ('time', models.TimeField(verbose_name='Öğün Saati')),
                ('foods', models.TextField(verbose_name='Yiyecekler')),
                ('calories', models.IntegerField(verbose_name='Kalori')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='home.dietprogram', verbose_name='Diyet Programı')),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Çalışan'), ('client', 'Danışan')], default='client', max_length=10, verbose_name='Kullanıcı Tipi')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Boy (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kilo (kg)')),
                ('health_conditions', models.TextField(blank=True, verbose_name='Sağlık Durumu')),
                ('allergies', models.TextField(blank=True, verbose_name='Alerjiler')),
                ('medications', models.TextField(blank=True, verbose_name='Kullanılan İlaçlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.AddField(
            model_name='dietprogram',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_programs', to='home.userprofile', verbose_name='Danışan'),
        ),
        migrations.AddField(
            model_name='dietprogram',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_programs', to='home.userprofile', verbose_name='Çalışan'),
        ),
    ]
