# Generated by Django 5.1.7 on 2025-03-31 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_dietprogram_alter_footersettings_footer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='content_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='documents',
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='homepage_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(default='Menekşeler', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='documents',
            field=models.ManyToManyField(blank=True, to='home.document'),
        ),
    ]
